---
- name: # command line type of variable
  hosts: all
  become: yes
  tasks:
     - name: add user and apply passwd
       user:
         name: "{{ us }}"
         state: present
         password: "{{ pw | password_hash('sha512') }}"
           

