---
- name: # 1st playbook for ansible managed node
  hosts: all
  gather_facts: false
  tasks:
     - name: creating directory
       file:
         path: /tmp/data
         state: directory
     - name: copying file 
       copy:
         src: /etc/fstab
         dest: /tmp/data
         mode: 0777
         owner: root
     - name: configured firewalld
       import_tasks: /playbook/firewall.yml
     - name: installed httpd
       import_tasks: /playbook/import.yml

