---
- name: #list playbook for all hosts 
  hosts: all
  gather_facts: true
  tasks:
     - name: installing firewalld on all managed nodes
       yum:
         name: httpd
         state: installed

